project_id = "vlepenxinekoljxecomr"

[functions.public-cliente-signin]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.confirm-password-reset]
verify_jwt = false

[functions.admin-delete-cliente]
verify_jwt = false

[functions.bot-wpp-proxy]
verify_jwt = false
