// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlepenxinekoljxecomr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZXBlbnhpbmVrb2xqeGVjb21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNjI0NDksImV4cCI6MjA5MDYzODQ0OX0.5U3grLWxVeHl2JnuTRWh4P3lPmiv04YAOFosjDZmjMA";
const SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZXBlbnhpbmVrb2xqeGVjb21yIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTA2MjQ0OSwiZXhwIjoyMDkwNjM4NDQ5fQ.n-vDPXUpnGZOEBpZJpzQ5TYEQSQwbWWPwAk3ShhYWnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    // Heartbeat reduzido ao máximo para minimizar tráfego keep-alive no NANO
    heartbeatIntervalMs: 60000,
    // Limita eventos processados por segundo (evita picos de I/O no NANO)
    eventsPerSecond: 2,
    // Timeout maior para reconexão — evita loop de reconnect que abre novas conexões
    reconnectAfterMs: (tries: number) => Math.min(tries * 2000, 30000),
  },
  db: {
    // Usa o connection pooler (Supavisor) via REST para todas as queries HTTP
    // Isso NÃO afeta o Realtime (que usa WebSocket), mas reduz conexões de queries
    schema: 'public',
  },
  global: {
    headers: {
      // Força o uso do pooler no lado do PostgREST
      'x-connection-encrypted': 'true',
    },
  },
});

// Cliente admin com permissão total — usado apenas no painel admin
// Ignora RLS (Row Level Security) automaticamente
export const supabaseAdmin = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    storageKey: 'sb-admin-no-session',
  },
  global: {
    headers: {
      Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
    },
  },
});